[package]
name = "remnantsofsiren/partysync"
version = "0.0.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
exclude = ["test", "Packages", "build", "test.project.json", "selene.toml", "README.md", ".gitignore", ".vscode"]
description = """
    PartySync aims to help with Party Systems, both persistant and non persistant

    Api Page: https://remnantsofsiren.github.io/PartySync
"""

[place]
shared-packages = "game.ReplicatedStorage.Packages"

[dependencies]
Signal = "data-oriented-house/lemonsignal@1.10.0"
Promise = "evaera/promise@4.0.0"